apiVersion: syncset.gatekeeper.sh/v1alpha1
kind: SyncSet
metadata:
  name: syncset-ns
  namespce: openshift-gatekeeper-system
spec:
  gvks:
    - group: ""
      version: "v1"
      kind: "Namespace"
