apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: namespaces-must-have-label
  namespace: acm-policies
spec:
  disabled: false
  remediationAction: inform
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-namespaces-zm-label
        spec:
          namespaceSelector:
            matchExpressions:
              - key: plaftform-onboarded
                operator: In
                values:
                  - "true"
          remediationAction: inform
          severity: medium
          object-templates-raw: |
            {{- range (lookup "v1" "Namespace" "" "" "platform-onboarded").items }}
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: {{ .metadata.name }}
                  labels:
                    zm-enforced: true
            {{- end }}

