---
apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gk-policy-generator-require-zm
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
  consolidateManifests: false
  informGatekeeperPolicies: false
  policySets:
    - gk-zm
placementBindingDefaults:
  name: "gk-require-zm-binding"

policies:
  - name: gk-require-zm-for-pods
    remediationAction: enforce
#     dependencies:
#       - name: "gatekeeper-instance"
#         compliance: "Compliant"
    manifests:
      - path: manifests/template.yaml
      - path: manifests/constraint.yaml

policySets:
  - name: gk-zm
    placement:
      placementName: "all-clusters"
